name: spread
description: A new Flutter project.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: '>=3.0.6 <4.0.0'

dependencies:
  flutter:
    sdk: flutter


  cupertino_icons: ^1.0.2
  go_router: ^9.0.3
  flutter_riverpod: ^2.3.6
  firebase_core: ^2.15.0
  google_fonts: ^5.1.0
  url_launcher: ^6.1.12
  cloud_firestore: ^4.8.3
  freezed: ^2.4.1
  freezed_annotation: ^2.4.1
  json_annotation: ^4.8.1
  dotted_decoration: ^2.0.0
  flutter_svg: ^2.0.7
  cached_network_image: ^3.2.3
  share_plus: ^7.1.0

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0
  build_runner: ^2.4.6
  json_serializable: ^6.7.1


flutter:

  uses-material-design: true

  assets:
    - assets/icons/
    - assets/icons/profile-icons/
    - assets/images/

scripts:
  generate_code: dart run build_runner build -d
  build_staging_apk: flutter build apk -t lib/main_stage.dart --flavor stage --dart-define-from-file=config_stage.json
  build_prod_apk: flutter build apk -t lib/main_prod.dart --flavor prod